### PR TITLE
Python2 > 3: GSP600 - Build a Nearby Business Search Service with Google Maps Platform 

### PR DESCRIPTION
**Pull request by swetasingh-tudip**
- Updated the app.yaml file with python3.

### CODE REVIEW

**Comment by mylenebiddle** [comment]
@wangela can you review and merge this?

**Comment by seanlubbers1** [comment]
Bump @wangela

**Comment by seanlubbers1** [comment]
Friendly ping on this @wangela

**Comment by mylenebiddle** [comment]
@amuramoto would be able to merge this? We have a dependency on this code in a Qwiklabs lab that we'd like to have updated to Python 3. Thanks!

**Pull request merged**
